### ISSUE TITLE
Hide cancel button [Question] 

### ISSUE THREAD

**Issue by mohammadaaqib** [formio/angular#774]
hi i wana hide cancel button in wizards in angular 
`  options = {buttonSettings: {showCancel: false}`
is not working 
 I am creating form this way 
 `<formio [form]="formConfig"   [options]="options" (submit)="onSubmit($event)"></formio>`

**Comment by davideginna** [comment]
i found this solution

```css
.formio-form .formio-wizard-nav-container.list-inline {
  display: none;
}
```
